import { createLocalResponsiveMedia } from '@/utils/helpers/responsiveMedia';
import type { ResponsiveMediaVariant } from '@/utils/types/responsiveMedia';

const LARGE_SIZES = '(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 1200px';
const CARD_SIZES = '(max-width: 768px) 100vw, 25vw';
const SMALL_CARD_SIZES = '(max-width: 768px) 50vw, 160px';
const AVATAR_SIZES = '(max-width: 768px) 96px, 120px';

const largeVariants = (name: string): ResponsiveMediaVariant[] => [
  { src: `/assets/generated/landing/${name}-480.jpg`, width: 480 },
  { src: `/assets/generated/landing/${name}-768.jpg`, width: 768 },
  { src: `/assets/generated/landing/${name}-1200.jpg`, width: 1200 },
];

const smallVariants = (name: string): ResponsiveMediaVariant[] => [
  { src: `/assets/generated/landing/${name}-160.jpg`, width: 160 },
  { src: `/assets/generated/landing/${name}-320.jpg`, width: 320 },
  { src: `/assets/generated/landing/${name}-480.jpg`, width: 480 },
];

export const LANDING_MEDIA = {
  heroDesktop: createLocalResponsiveMedia({
    alt: 'We Better dashboard preview',
    src: '/assets/images/hero/hero_main.webp',
    width: 1440,
    height: 810,
    sizes: LARGE_SIZES,
    variants: largeVariants('hero-hero-main'),
  }),
  heroMobile: createLocalResponsiveMedia({
    alt: 'We Better mobile app interface',
    src: '/assets/images/hero/mobile/app_hero_mobile.webp',
    width: 750,
    height: 1334,
    sizes: '(max-width: 768px) 100vw, 480px',
    variants: [
      { src: '/assets/generated/landing/hero-app-hero-mobile-320.jpg', width: 320 },
      { src: '/assets/generated/landing/hero-app-hero-mobile-480.jpg', width: 480 },
      { src: '/assets/generated/landing/hero-app-hero-mobile-768.jpg', width: 768 },
    ],
  }),
  heroFloating: {
    menHiking: createLocalResponsiveMedia({
      alt: 'Men hiking',
      src: '/assets/generated/landing/hero-men-hiking-320.jpg',
      poster: '/assets/generated/landing/hero-men-hiking-320.jpg',
      width: 400,
      height: 400,
      sizes: SMALL_CARD_SIZES,
      variants: smallVariants('hero-men-hiking'),
    }),
    womanPlanning: createLocalResponsiveMedia({
      alt: 'Woman planning',
      src: '/assets/generated/landing/hero-woman-planning-320.jpg',
      poster: '/assets/generated/landing/hero-woman-planning-320.jpg',
      width: 400,
      height: 400,
      sizes: SMALL_CARD_SIZES,
      variants: smallVariants('hero-woman-planning'),
    }),
    coupleRelationship: createLocalResponsiveMedia({
      alt: 'Couple relationship',
      src: '/assets/images/hero/couple_relationship.webp',
      width: 400,
      height: 400,
      sizes: SMALL_CARD_SIZES,
      variants: smallVariants('hero-couple-relationship'),
    }),
    manMeditating: createLocalResponsiveMedia({
      alt: 'Man meditating',
      src: '/assets/images/hero/man_meditating.webp',
      width: 400,
      height: 400,
      sizes: SMALL_CARD_SIZES,
      variants: smallVariants('hero-man-meditating'),
    }),
  },
  galleryFallbacks: {
    body: createLocalResponsiveMedia({
      alt: 'Woman running',
      src: '/assets/generated/landing/gallery-body-768.jpg',
      poster: '/assets/generated/landing/gallery-body-768.jpg',
      width: 1200,
      height: 900,
      sizes: LARGE_SIZES,
      variants: largeVariants('gallery-body'),
    }),
    mind: createLocalResponsiveMedia({
      alt: 'Woman thinking',
      src: '/assets/images/gallery/mind.webp',
      width: 1200,
      height: 900,
      sizes: LARGE_SIZES,
      variants: largeVariants('gallery-mind'),
    }),
    family: createLocalResponsiveMedia({
      alt: 'A family of 3',
      src: '/assets/images/gallery/family.webp',
      width: 1200,
      height: 900,
      sizes: LARGE_SIZES,
      variants: largeVariants('gallery-family'),
    }),
    care: createLocalResponsiveMedia({
      alt: 'A woman taking care of herself',
      src: '/assets/images/gallery/care.webp',
      width: 1200,
      height: 900,
      sizes: LARGE_SIZES,
      variants: largeVariants('gallery-care'),
    }),
    career: createLocalResponsiveMedia({
      alt: 'A man in a suit',
      src: '/assets/images/gallery/career.webp',
      width: 1200,
      height: 900,
      sizes: LARGE_SIZES,
      variants: largeVariants('gallery-career'),
    }),
    spirit: createLocalResponsiveMedia({
      alt: 'A woman meditating',
      src: '/assets/images/gallery/spirit.webp',
      width: 1200,
      height: 900,
      sizes: LARGE_SIZES,
      variants: largeVariants('gallery-spirit'),
    }),
    gallery1: createLocalResponsiveMedia({
      alt: 'A man wearing headphones',
      src: '/assets/images/gallery/gallery_1_small.webp',
      width: 480,
      height: 480,
      sizes: CARD_SIZES,
      variants: smallVariants('gallery-1-small'),
    }),
    gallery2: createLocalResponsiveMedia({
      alt: 'A woman working on her laptop',
      src: '/assets/images/gallery/gallery_2_small.webp',
      width: 480,
      height: 480,
      sizes: CARD_SIZES,
      variants: smallVariants('gallery-2-small'),
    }),
    gallery3: createLocalResponsiveMedia({
      alt: 'A woman reflecting in a gallery setting',
      src: '/assets/images/gallery/gallery_3_small.webp',
      width: 480,
      height: 480,
      sizes: CARD_SIZES,
      variants: smallVariants('gallery-3-small'),
    }),
    gallery4: createLocalResponsiveMedia({
      alt: 'Men reading a book',
      src: '/assets/images/gallery/gallery_4_small.webp',
      width: 480,
      height: 480,
      sizes: CARD_SIZES,
      variants: smallVariants('gallery-4-small'),
    }),
    gallery5: createLocalResponsiveMedia({
      alt: 'A woman holding books',
      src: '/assets/images/gallery/gallery_5_small.webp',
      width: 480,
      height: 480,
      sizes: CARD_SIZES,
      variants: smallVariants('gallery-5-small'),
    }),
    gallery6: createLocalResponsiveMedia({
      alt: 'Men talking to a woman',
      src: '/assets/images/gallery/gallery_6_small.webp',
      width: 480,
      height: 480,
      sizes: CARD_SIZES,
      variants: smallVariants('gallery-6-small'),
    }),
  },
  highlights: {
    goals: createLocalResponsiveMedia({
      alt: 'Goals',
      src: '/assets/images/highlights/goals.webp',
      width: 1200,
      height: 800,
      sizes: LARGE_SIZES,
      variants: largeVariants('highlights-goals'),
    }),
    relationships: createLocalResponsiveMedia({
      alt: 'Relationships',
      src: '/assets/images/highlights/relationship.webp',
      width: 1200,
      height: 800,
      sizes: LARGE_SIZES,
      variants: largeVariants('highlights-relationship'),
    }),
    resilience: createLocalResponsiveMedia({
      alt: 'Resilience',
      src: '/assets/images/highlights/resilience.webp',
      width: 1200,
      height: 800,
      sizes: LARGE_SIZES,
      variants: largeVariants('highlights-resilience'),
    }),
    career: createLocalResponsiveMedia({
      alt: 'Career',
      src: '/assets/images/highlights/career.webp',
      width: 1200,
      height: 800,
      sizes: LARGE_SIZES,
      variants: largeVariants('highlights-career'),
    }),
    finances: createLocalResponsiveMedia({
      alt: 'Finances',
      src: '/assets/images/highlights/finances.webp',
      width: 1200,
      height: 800,
      sizes: LARGE_SIZES,
      variants: largeVariants('highlights-finances'),
    }),
  },
  showcase: {
    tracking: createLocalResponsiveMedia({
      alt: 'Tracking',
      src: '/assets/images/showcase/belt/tracking.png',
      width: 600,
      height: 450,
      sizes: CARD_SIZES,
      variants: smallVariants('showcase-tracking'),
    }),
    ebooks: createLocalResponsiveMedia({
      alt: 'E-Books',
      src: '/assets/images/showcase/belt/ebooks.png',
      width: 600,
      height: 450,
      sizes: CARD_SIZES,
      variants: smallVariants('showcase-ebooks'),
    }),
    insights: createLocalResponsiveMedia({
      alt: 'Insights',
      src: '/assets/images/showcase/belt/insights.png',
      width: 600,
      height: 450,
      sizes: CARD_SIZES,
      variants: smallVariants('showcase-insights'),
    }),
    networking: createLocalResponsiveMedia({
      alt: 'Networking',
      src: '/assets/images/showcase/belt/networking.png',
      width: 600,
      height: 450,
      sizes: CARD_SIZES,
      variants: smallVariants('showcase-networking'),
    }),
    newsletter: createLocalResponsiveMedia({
      alt: 'Newsletter',
      src: '/assets/images/showcase/belt/newsletter.png',
      width: 600,
      height: 450,
      sizes: CARD_SIZES,
      variants: smallVariants('showcase-newsletter'),
    }),
    spreadsheets: createLocalResponsiveMedia({
      alt: 'Spreadsheets',
      src: '/assets/images/showcase/belt/spreadsheets.png',
      width: 600,
      height: 450,
      sizes: CARD_SIZES,
      variants: smallVariants('showcase-spreadsheets'),
    }),
    playlists: createLocalResponsiveMedia({
      alt: 'Playlists',
      src: '/assets/images/showcase/belt/playlists.webp',
      width: 600,
      height: 450,
      sizes: CARD_SIZES,
      variants: smallVariants('showcase-playlists'),
    }),
  },
  community: {
    profile1: createLocalResponsiveMedia({
      alt: 'Community member profile 1',
      src: '/assets/images/community/community_1.webp',
      width: 98,
      height: 1024,
      sizes: AVATAR_SIZES,
    }),
    profile2: createLocalResponsiveMedia({
      alt: 'Community member profile 2',
      src: '/assets/images/community/community_2.webp',
      width: 98,
      height: 1024,
      sizes: AVATAR_SIZES,
    }),
    profile3: createLocalResponsiveMedia({
      alt: 'Community member profile 3',
      src: '/assets/images/community/community_3.webp',
      width: 98,
      height: 1024,
      sizes: AVATAR_SIZES,
    }),
    profile4: createLocalResponsiveMedia({
      alt: 'Community member profile 4',
      src: '/assets/images/community/community_4.webp',
      width: 98,
      height: 1024,
      sizes: AVATAR_SIZES,
    }),
    profile5: createLocalResponsiveMedia({
      alt: 'Community member profile 5',
      src: '/assets/images/community/community_5.webp',
      width: 98,
      height: 1024,
      sizes: AVATAR_SIZES,
    }),
    profile6: createLocalResponsiveMedia({
      alt: 'Community member profile 6',
      src: '/assets/images/community/community_6.webp',
      width: 98,
      height: 1024,
      sizes: AVATAR_SIZES,
    }),
  },
  testimonies: {
    testimony1: createLocalResponsiveMedia({
      alt: 'Ayesha K., 27, Student',
      src: '/assets/images/testimonies/testimony_1.webp',
      width: 160,
      height: 160,
      sizes: AVATAR_SIZES,
      variants: smallVariants('testimony-1'),
    }),
    testimony2: createLocalResponsiveMedia({
      alt: 'Chris T., 31, Software Developer',
      src: '/assets/images/testimonies/testimony_2.webp',
      width: 160,
      height: 160,
      sizes: AVATAR_SIZES,
      variants: smallVariants('testimony-2'),
    }),
    testimony3: createLocalResponsiveMedia({
      alt: 'Emily S., 29, Marketing Professional',
      src: '/assets/images/testimonies/testimony_3.webp',
      width: 160,
      height: 160,
      sizes: AVATAR_SIZES,
      variants: smallVariants('testimony-3'),
    }),
  },
  preFooter: createLocalResponsiveMedia({
    alt: 'Interactive preview of We Better platform showcasing creative tools and workspace',
    src: '/assets/images/prefooter/prefooter.webp',
    width: 1200,
    height: 900,
    sizes: LARGE_SIZES,
    variants: largeVariants('prefooter'),
  }),
} as const;

export default LANDING_MEDIA;
